package com.wally.kissmod;

public enum KissValidationResult {
    VALID,
    SOURCE_BLOCKED_STATE,
    SOURCE_OPTED_OUT,
    SOURCE_COOLDOWN,
    TARGET_MISSING,
    TARGET_OPTED_OUT,
    TARGET_BUSY_OR_COOLDOWN,
    TARGET_BLOCKED_STATE,
    TOO_FAR,
    NOT_LOOKING,
    NO_LINE_OF_SIGHT
}
